# Generated by Django 5.1.1 on 2024-10-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_students_delete_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.CharField(choices=[('BA', 'BA'), ('B.COM', 'B.COM'), ('MBA', 'MBA'), ('CA', 'CA')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
